### ISSUE TITLE
Choose a license, please

### ISSUE THREAD

**Issue by einsweniger** [cnr-isti-vclab/ReviewerNet#149]
I've been looking at this for quite a while now and I wanted to reuse and modify some of your code. 
But you did not choose a license, preventing me to use your intellectual property.
For guidance and github integration, I can wholeheartdly recommend https://choosealicense.com/ to choose and immediately apply the licensing information.

best regards,
-1

**Comment by hybrs** [comment]
A GNU3 license will be available with the next update.

Thank you for your feedback
